Repository tenders-exposed/elvis-ember, pull requests merged in 2019-03, with the labels that each got.

#472 Tidyup
  app/components/elvis-nav.js
  app/routes/network/new.js
  app/styles/_network.scss
  app/styles/_variables.scss
  app/styles/app.scss
  app/styles/application.scss
  app/styles/components/box-details.scss
  app/styles/components/elvis-data-table.scss
  app/styles/general/navbar.scss
  app/styles/general/network.scss
  app/styles/network/show.scss
  app/styles/network/show/details.scss
  app/styles/network/vis/navigation.scss
  app/templates/application.hbs
  app/templates/components/box-details.hbs
  app/templates/components/elvis-nav.hbs
  app/templates/network.hbs
  app/templates/network/show.hbs
  app/templates/network/show/details.hbs
  app/templates/partials/links-footer.hbs
  app/templates/partials/main-footer.hbs
  app/templates/partials/main-nav.hbs
Labels: UX, design, housekeeping, to review

#484 Legend refactor
  app/controllers/network/show.js
  app/styles/_loading.scss
  app/styles/_network.scss
  app/styles/_variables.scss
  app/styles/app.scss
  app/styles/components/elvis-data-table.scss
  app/styles/components/progress-bar.scss
  app/styles/general/modal.scss
  app/styles/network/legend.scss
  app/styles/network/show.scss
  app/styles/network/show/details.scss
  app/templates/application.hbs
  app/templates/loading.hbs
  app/templates/network/new.hbs
  app/templates/network/show.hbs
  app/templates/network/show/details.hbs
Labels: 3 - Review, to review

#488 Fix ESLint rules and Travis builds
  .eslintrc.js
  app/components/elvis-select-guru.js
  app/controllers/network/new.js
  app/services/client.js
  app/services/cpv.js
  app/services/me.js
  app/services/network.js
  app/services/songs.js
  commitlint.config.js
  package-lock.json
  package.json
  tests/integration/components/qb-no-option-test.js
  tests/unit/initializers/inject-notifications-test.js
  tests/unit/instance-initializers/client-test.js
  tests/unit/instance-initializers/me-test.js
  tests/unit/instance-initializers/network-test.js
  tests/unit/instance-initializers/session-test.js
  tests/unit/routes/404-test.js
  tests/unit/routes/about-test.js
  tests/unit/routes/account/login-test.js
  tests/unit/routes/account/oauth-callback-test.js
  tests/unit/routes/contact-test.js
  tests/unit/routes/examples-test.js
  tests/unit/routes/features-test.js
  tests/unit/routes/gallery-test.js
  tests/unit/routes/terms-conditions-test.js
Labels: to review

#487 Fix package-lock.json and images paths
  app/controllers/network/show.js
  app/templates/network/new.hbs
  package-lock.json
Labels: to review
